# Generated by Django 5.1.2 on 2024-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Название бренда')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.CharField(max_length=255, verbose_name='Цена товара')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет товара')),
                ('rating', models.FloatField(verbose_name='Рейтинг товара')),
                ('number_of_ratings', models.IntegerField(verbose_name='Количество оценок')),
                ('options', models.JSONField(verbose_name='Опции')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
